// Copyright 2026 VERITAS Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// SouffleWorkerMain.cpp — the compiled recursive-WPA worker entry point.
//
// Links the two compiled V2 rule bundles (reachability and may-write) plus the
// semantic-key functor library, and runs the one named by --component. Each
// bundle is generated by `souffle -g` and compiled with __EMBEDDED_SOUFFLE__,
// which suppresses its `main` and registers a ProgramFactory under the program
// name derived from its output filename (v2_reach / v2_maywrite).
//
// This is the only executable that links Souffle. It reads relation inputs from
// -F and writes derived relations and the witness relation to -D, exactly the
// contract RelationIo writes and reads. It is compiled with exceptions and RTTI
// enabled because Souffle throws std::exception on failure and uses RTTI.

#include <cstdlib>
#include <cstring>
#include <iostream>
#include <string>
#include <string_view>

#include "souffle/SouffleInterface.h"

namespace {

// Maps a component argument to the registered program name. These names are the
// output filenames the build generates the bundles from (v2_reach.cpp /
// v2_maywrite.cpp), sanitized by Souffle's synthesiser.
const char* ProgramNameForComponent(std::string_view component) {
  if (component == "reachability") return "v2_reach";
  if (component == "memory-effects") return "v2_maywrite";
  return nullptr;
}

void PrintUsage(std::ostream& os) {
  os << "usage: veritas-souffle-worker"
        " --component=<reachability|memory-effects>"
        " -F <input-dir> -D <output-dir> [--jobs N]\n";
}

}  // namespace

int main(int argc, char** argv) {
  std::string component;
  std::string input_dir;
  std::string output_dir;
  std::size_t jobs = 1;

  for (int i = 1; i < argc; ++i) {
    const std::string_view arg(argv[i]);
    if (arg.starts_with("--component=")) {
      component = std::string(arg.substr(std::strlen("--component=")));
    } else if (arg == "-F" && i + 1 < argc) {
      input_dir = argv[++i];
    } else if (arg == "-D" && i + 1 < argc) {
      output_dir = argv[++i];
    } else if (arg == "--jobs" && i + 1 < argc) {
      jobs = static_cast<std::size_t>(std::strtoull(argv[++i], nullptr, 10));
    } else if (arg == "-h" || arg == "--help") {
      PrintUsage(std::cout);
      return 0;
    } else {
      std::cerr << "veritas-souffle-worker: unknown argument: " << arg << '\n';
      PrintUsage(std::cerr);
      return 2;
    }
  }

  const char* program_name = ProgramNameForComponent(component);
  if (program_name == nullptr) {
    std::cerr << "veritas-souffle-worker: unknown component: '" << component
              << "'\n";
    PrintUsage(std::cerr);
    return 2;
  }

  souffle::SouffleProgram* program =
      souffle::ProgramFactory::newInstance(program_name);
  if (program == nullptr) {
    std::cerr << "veritas-souffle-worker: no compiled program registered for '"
              << program_name << "'\n";
    return 3;
  }

  program->setNumThreads(jobs);
  try {
    program->runAll(input_dir, output_dir, /*performIO=*/true,
                    /*pruneImdtRels=*/true);
  } catch (const std::exception& e) {
    std::cerr << "veritas-souffle-worker: evaluation failed: " << e.what()
              << '\n';
    delete program;
    return 1;
  }
  delete program;
  return 0;
}
